### ISSUE TITLE
information

### ISSUE THREAD

**Issue by turkfuat** [hjyai94/Half_Pathway_DeepMedic#1]
hello
1. Can we use this code in renal tumors?
2. How to run gpu instead of cpu testing stage ?(because CPU MIB is insufficient)
tahnk you

**Comment by hjyai94** [comment]
Hello, 
1. You can use this code to other tumor datasets, but you have to change the Dataloader in dataset.py.
2. The code mainly uses GPU in the testing stage, so it doesn't need too much CPU memory.

ps: if the repo is helpful for you, you can give me a star.

**Comment by hjyai94** [comment]
> hello
> 
> 1. Can we use this code in renal tumors?
> 2. How to run gpu instead of cpu testing stage ?(because CPU MIB is insufficient)
>    tahnk you

**Comment by turkfuat** [comment]
1.cpu cache memory (out of memory) in the last section is insufficient
2. Can you help me when I change the code for kidney tumors?

**Comment by hjyai94** [comment]
> 1.cpu cache memory (out of memory) in the last section is insufficient
> 2. Can you help me when I change the code for kidney tumors?
 I rerun the code, and it uses about 7GB GPU memory and 16GB CPU memory in testing stage.
