### ISSUE TITLE
help

### ISSUE THREAD

**Issue by turkfuat** [hjyai94/Half_Pathway_DeepMedic#3]
1.cpu cache memory (out of memory) in the last section is insufficient
2. Can you help me when I change the code for kidney tumors?

**Comment by hjyai94** [comment]
1. I re-run the code, and it uses about 7GB GPU memory and 16GB CPU memory in the testing stage.
2. If you want to use this code to other datasets, you can refer [Pytorch tutorial](https://pytorch.org/tutorials/index.html) especial for Dataloader.
